#necessary
baseURL: https://porteight.netlify.app/
languageCode: en-us
title: Porteight
taxonomies:
  category: categories
  tag: tags
summaryLength: 20
paginate: 8
paginatePath:

# menu
menu:
  main:
    - identifier: work
      title: work
      name: Work
      url: /works
      weight: 10
    - identifier: about
      title: about
      name: About
      url: /pages/about
      weight: 20
    - identifier: blog
      title: blog
      name: Blog
      url: /blogs
      weight: 30
    - identifier: contact
      title: contact
      name: Contact
      url: /pages/contact
      weight: 40

params:
  description: Welcome to my portfolio! I am a digital artist and freelancer, specializing in creating beautiful, unique designs for a variety of clients. With years of experience in the field, I have developed a strong set of skills in graphic design, illustration, and digital art. My passion for art and design shines through in every project I take on, and I strive to deliver exceptional results for my clients every time.
  workCopy: Experience the benefits of hiring a skilled freelancer for all your creative and professional needs - from website design to copywriting and more.
  blogCopy: Stay updated with the latest insights, tips, and tricks from our talented team of freelancers through our informative and engaging blog posts.
  contactCopy: We love to get in touch with new people. Whether you are a potential customer, partner or someone else, we love to hear from you!
  location: Jl. Pahlawan II Komplek Mercusuar Tower, Sukolilo, Surabaya, Jawa Timur.
  email: hi@example.com
  phone: +62 851 6578 9876
  instagram: kuunnnte
  behance: kuunnnte
  linkedin: kuunnnte
  github: kuunnnte
  telegram: kuunnnte
  youtube: UCENcmRnetYH0m387ZS3bpyw
